### PR TITLE
Fixed unit shaking and Add anti-overlap feature

### PR DESCRIPTION
**Pull request by JohnFarmer**
Shaking: Units will "shaking" when not moving, for __(unit[0], unit[1])__ are float but the condition in Line 830 is only for int.

Overlap: Units may overlap each other and become united when having a same destination. Added a check when unit is not moving and force unit to random walk a little bit when unit are too close to other unit. It's rough yet just works, I'll impove it later. (but it is fun that I can make a unit by combining a lot of unit)

### CODE REVIEW

**Comment by honzi** [comment]
I like what these commits do, but there are still formatting issues. I will probably create a repository for formatting standards used in iterami repositories so I can give you a better reference. I'll leave this open for now.

I also think the functions and variables could use better names, but that probably now applies to the entire repository...

**Comment by JohnFarmer** [comment]
Hi Jan,
     RTS-2D.htm is a great project for those who have no idea about game 
programming.
     I've created another repo which is almost the same as RTS-2D.htm, 
expect that running all logic stuff on the server side(powerd by 
node.js), you could check it out on vetrm.net.
     The repo forked from RTS-2D.htm will be used to push back 
improvement to you, I will try my best to adopt iterami formatting standard.
     As none-native English speaker like us, it's really hard to name 
things, but there may at least be a unified naming rule which is up to 
you :).

**Comment by honzi** [comment]
Thank you for your continued interest. Sorry for the delayed reply.

I have a version ready to push that implements a modified version of your changes. I fixed some formatting issues and modified some changes to make it more consistent with the rest of the repository. There was a bug that allowed units to move past the edges of the level when splitting apart, which I plan to fix by adding in a validate_destination() function.

Are you willing to allow your changes to be merged into a public domain repository? Your changes will be made public domain as well, as all code within this repository is licensed as CC0. If you are willing then I will merge your changes and then push my changes afterwards so you will still be listed as a contributor.

I am glad you find this repository useful, but be careful. The code in this repository still needs a lot of work and may not follow best practices yet.

**Comment by JohnFarmer** [comment]
I agree that it's not a good idea to directly set destination, and I'll talk to you if I find there is other thing need to validate before set.

You could just merge the code, I read about what does CC0 license means the first time I saw this repo.

Your comments are realy helpful, actually the code itself is quite simple for nearly 2/3 of code is about drawing and logic(which are only about to iterating everything). I'll keep working on the client/server branch and your suggestions are welcome :)

**Comment by honzi** [comment]
Thanks! I pushed up my changes, so let me know if you have any questions about that.

**Pull request merged**
